import Header from '../components/Header'
import Footer from '../components/Footer'
import 'bootstrap/dist/css/bootstrap.min.css';
import "@/assets/scss/globals.scss";

export const metadata = {
  title: "Liaisonbank",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-scroll-behavior="smooth"> 
      <body className="flex flex-col min-h-screen bg-gray-50">
        <Header />
        <main className="flex-grow">
            {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
